### PR TITLE
change  userHome to direct to /award

### PR DESCRIPTION
**Pull request by mcclungc**
change link on userHome view to connect to createaward view with db functionality

### CODE REVIEW

**Comment by berryte** [comment]
Already got this changed.

**Comment by mcclungc** [comment]
It's not a big deal, but in order for the create award form to connect with the database, the href  with  /create-award on userHome and userHistory views should direct to /award instead - right now the form loads but the dropdown fields from the database don't populate.


That may be due to a problem with the way I wrote my code. I will work on fixing it after this week.


If you could make this change in the meantime, the demo will work better for the graders because they will be able to add a record. Would that be okay? Thanks.

**Comment by berryte** [comment]
We would have to change it in a few places. Let me do that right now. It is
in the navigation too.

**Comment by berryte** [comment]
I see what you are saying. I got the hyperlinked fixed then. It should work
now.

**Comment by mcclungc** [comment]
Thanks!

I will have a draft of the user instructions posted to our Google Docs later tonight and we can polish it as needed.

**Pull request closed without merging**
